ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
onlyBuiltDependencies:
  - sqlite3
overrides:
  '@hono/node-server@<1.19.13': '>=1.19.13'
  '@tootallnate/once@<2.0.1': '>=2.0.1'
  postcss@<8.5.10: '>=8.5.10'
  tar@<7.5.7: '>=7.5.7'
  tar@<7.5.8: '>=7.5.8'
  tar@<=7.5.10: '>=7.5.11'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
  tar@<=7.5.9: '>=7.5.10'
  undici@<6.23.0: '>=6.23.0'
  undici@<6.24.0: '>=6.24.0'
